project:
  type: website
  output-dir: docs

website:
  title: "Motivation & Democracy Data Hub"
 #image: "datahublogo.png"
  favicon: "favicon.png"
  # google-analytics: "G-FV9Z7SDZ0M"
 # open-graph: true
  repo-actions: [edit, issue]
  twitter-card: true
  sidebar: false 
  #site-url: https://quarto.org
  # sidebar:
  #   search: true
    # style: "docked"
  page-footer:
    center: "© 2025 Joachim Waterschoot"
  navbar:
    background: light
    logo: "datahublogo.png"
    logo-alt: "logo."
    collapse-below: lg
    right:
      - icon: github
        href: https://github.com/Watjoa
        aria-label: Quarto GitHub
    left:
      - text: "Note"
        href: index.qmd#concept-note
      - text: "Explore"
        href: index.qmd#explore
      - text: "Documentation"
        href: index.qmd#documentation
      - text: "Governance & ethics"
        href: index.qmd#governance-ethics
    

bibliography: references.bib

format:
  html:
    respect-user-color-scheme: true
    toc: false
    page-layout: full
    # grid:
    #   body-width: 1100px     # your desired content width
    #   margin-width: 0px      # remove margin column
    #   sidebar-width: 50px     # ensure no sidebar column is reserved
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    css: styles.css
    # include-in-header:
    #   - text: |
    #       <script src="https://cdn.jsdelivr.net/gh/posit-dev/supported-by-posit/js/badge.min.js"
    #         data-light-bg="#E8EDF2"
    #         data-light-text="#404041"
    #         data-light-lt="#ee6331"
    #         data-light-gt="#447099"
    #         data-dark-bg="#333333"
    #         data-dark-lt="#ffffff"
    #         data-dark-gt="#ffffff"></script>
    # include-after-body: js.html
    # grid:
    #   sidebar-width: 10px
    #   body-width: 1100px
    #   margin-width: 0px
    # smooth-scroll: true
    # lang: en
    # page-layout: full